nelmio_api_doc:
    html_config:
        assets_mode: 'bundle' # 'cdn', 'bundle', 'offline'
    cache:
        pool: cache.app
        item_id: nelmio_api_doc.docs
    models:
        use_jms: false
    documentation:
        servers:
            - url: https://magazine.wapinet.ru
              description: Production API
        info:
            title: Magazine
            description: Simple magazine
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

    areas:
        default:
            path_patterns: [ ^/api/public/(?!doc) ]
        private:
            path_patterns: [ ^/api/private/(?!doc) ]
