nelmio_api_doc:
    cache:
        pool: cache.app
        item_id: nelmio_api_doc.docs
    models:
        use_jms: false
    documentation:
        servers:
            - url: http://localhost
              description: Staging API
            - url: https://magazine.wapinet.ru
              description: Production API
        info:
            title: Magazine
            description: Simple magazine
            version: 0.2.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/public/
        public:
            path_patterns:
                - ^/api/public/
        private:
            path_patterns:
                - ^/api/private/
