services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/php/php.ini:/usr/local/etc/php/php.ini'
      - '.docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf'
      - '.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    container_name: magazine-php
    ports:
      - "9000:9000" # php-fpm
    expose:
      - "9001" # xdebug

  angie:
    build:
      context: ./.docker/angie
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/angie/app.conf:/etc/angie/http.d/default.conf'
    ports:
      - "80:80"
    container_name: magazine-angie
    depends_on:
      - php
