# Expose your documentation as JSON swagger compliant
app.openapi_api_public:
    path: /api/public/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.openapi_api_private:
    path: /api/private/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: private }

## Requires the Asset component and the Twig bundle
## $ composer require twig asset
app.openapi_ui_api_public:
    path: /api/public/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight, area: default }

app.openapi_ui_api_private:
    path: /api/private/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight, area: private }

